version : '3'
services:
 mysql-server:
  image: mysql
  ports:
   - "3310:3310"
  environment:
   - MYSQL_ROOT_PASSWORD=root
 node-app:
  build:
   context: .
   dockerfile: ./Dockerfile
  ports:
   - 3000:9229
  environment:
   - MYSQL_HOST=127.0.0.1
   - MYSQL_USER=oot
   - MYSQL_PASSWORD=root
   - MYSQL_DATABASE=ysql
   - MYSQL_PORT=3310