version : '3'
services:
 mysql-server:
  image: mysql
  ports:
   - "3310:3310"
  environment:
   - MYSQL_ROOT_PASSWORD=root
 node-app:
  build:
   context: .
   dockerfile: ./Dockerfile
  ports:
   - 3000:3000